{
 "title": "CriblVision",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics", "label": "Metrics Source", "query": "prometheus" },
   { "name": "logs", "label": "Log Source", "query": "loki" },
   {
    "name": "group",
    "label": "Group",
    "query": {
     "query": "label_values(cribl_logstream_system_cpu_perc,group)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(cribl_logstream_system_cpu_perc{group=\"$group\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Health Check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top View Worker Info over timeframe",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(avg by(job) (cribl_logstream_system_cpu_perc{group=\"$group\", instance=\"$host\"}), \"job\", \"CPU Usage\", \"job\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(increase(cribl_logstream_total_in_bytes{group=\"$group\", instance=\"$host\"}[$__range])) / 1000 / 1000,  \"job\", \"in MBytes\", \"job\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(increase(cribl_logstream_total_out_bytes{group=\"$group\", instance=\"$host\"}[$__range])) / 1000 / 1000 ,  \"job\", \"out MBytes\", \"job\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(increase(cribl_logstream_total_in_events{group=\"$group\", instance=\"$host\"}[$__range])) ,  \"job\", \"in Events\", \"job\", \"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum(increase(cribl_logstream_total_out_events{group=\"$group\", instance=\"$host\"}[$__range])) ,  \"job\", \"out Events\", \"job\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "max by(cribl_wp) (cribl_logstream_system_mem_rss{instance=\"$host\", group=\"$group\", job=\"LogStream\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(cribl_wp) (cribl_logstream_system_cpu_perc{instance=\"$host\", group=\"$group\", job=\"LogStream\"} /100 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PQ Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "max by(cribl_wp) (cribl_logstream_pq_queue_size{instance=\"$host\", group=\"$group\", job=\"LogStream\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cribl Stream Unhealthy Inputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "cribl_logstream_health_inputs{group=\"$group\", instance=\"$host\"} > 0",
     "legendFormat": "{{output}}"
    }
   ]
  },
  {
   "title": "Cluster communication errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "{service=\"Cribl\"} |= `` | json | logfmt | host=`$host` and group = `$group` and (level=\"error\" or level=\"warn\") and channel=\"clustercomm\""
    }
   ]
  },
  {
   "title": "Cribl Stream Unhealthy Outputs",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "count_values by(output) (\"values\", cribl_logstream_health_outputs{group=\"$group\", instance=\"$host\"} > 0)",
     "legendFormat": "{{output}}"
    }
   ]
  },
  {
   "title": "Worker process messages",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{service=\"Cribl\"} |= `` | json | logfmt | host = `$host` | message=~\".+arting.+\" and channel =~ \"[cC]ribl\""
    }
   ]
  },
  {
   "title": "Destinations with backpressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "max (cribl_logstream_backpressure_outputs{group=\"$group\", instance=\"$host\"}) by(output) > 0",
     "legendFormat": "{{output}}"
    }
   ]
  },
  {
   "title": "Blocked destinations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "max (cribl_logstream_blocked_outputs{group=\"$group\", instance=\"$host\"}) by(output) > 0",
     "legendFormat": "{{output}}"
    }
   ]
  },
  { "title": "Log Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Error Messages for $host",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{service=\"Cribl\"} |= `` | json | host = `$host` | level = `error`"
    }
   ]
  },
  {
   "title": "Error Messages for $host",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "{service=\"Cribl\"} |= `` | json | host = `$host` | level = `error`"
    }
   ]
  },
  {
   "title": "Info Messages for $host",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{service=\"Cribl\"} |= `` | json | host = `$host` | level = `info`"
    }
   ]
  },
  { "title": "Volume Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Route Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name) (cribl_logstream_route_in_events{group=\"$group\", instance=\"$host\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Route Events In",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (increase(cribl_logstream_route_in_events{group=\"$group\", instance=\"$host\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Route Events Out",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (increase(cribl_logstream_route_out_events{group=\"$group\", instance=\"$host\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Route MB In",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (increase(cribl_logstream_route_in_bytes{group=\"$group\", instance=\"$host\"}[1h])/1000/1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Route MB Out",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name) (increase(cribl_logstream_route_out_bytes{group=\"$group\", instance=\"$host\"}[1h])/1000/1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In MBytes by Route, Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(name) (cribl_logstream_route_in_bytes{group=\"$group\", instance=\"$host\"} / 1000 / 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In Events by Route, Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum by(name) (cribl_logstream_route_in_events{group=\"$group\", instance=\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out MBytes by Route, Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(name) (cribl_logstream_route_out_bytes{group=\"$group\", instance=\"$host\"} / 1000 / 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out Events by Route, Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "sum by(name) (cribl_logstream_route_out_events{group=\"$group\", instance=\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Reduction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum(increase(cribl_logstream_route_in_bytes{group=\"$group\", instance=\"$host\"}[$__range])) / (1000 * 1000)",
     "legendFormat": "Total MB In"
    },
    {
     "expr": "sum(increase(cribl_logstream_route_out_bytes{group=\"$group\", instance=\"$host\"}[$__range])) / (1000 * 1000)",
     "legendFormat": "Total MB Out"
    },
    {
     "expr": "(sum(increase(cribl_logstream_route_in_bytes{group=\"$group\", instance=\"$host\"}[$__range])) \r\n- sum(increase(cribl_logstream_route_out_bytes{group=\"$group\", instance=\"$host\"}[$__range])))\r\n/ (1000 * 1000)",
     "legendFormat": "MB Reduction"
    }
   ]
  },
  {
   "title": "Total Reduction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "100 * \r\n(sum(increase(cribl_logstream_route_in_bytes{group=\"$group\", instance=\"$host\"}[$__range])) \r\n- sum(increase(cribl_logstream_route_out_bytes{group=\"$group\", instance=\"$host\"}[$__range])))\r\n/ sum(increase(cribl_logstream_route_in_bytes{group=\"$group\", instance=\"$host\"}[$__range]))",
     "legendFormat": "% Reduction"
    }
   ]
  },
  { "title": "Thruput Introspection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Out Events by Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum by(output) (cribl_logstream_total_out_events{group=\"$group\", instance=\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes out by Output",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(output) (cribl_logstream_total_out_bytes{group=\"$group\", instance=\"$host\"}) / 1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU by Worker Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(cribl_wp) (cribl_logstream_system_cpu_perc{group=\"$group\", instance=\"$host\"})/100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events in by Input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "sum by(input) (cribl_logstream_total_in_events{group=\"$group\", instance=\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes in by Input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum by(input) (cribl_logstream_total_in_bytes{group=\"$group\", instance=\"$host\"}) / 1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}